### ISSUE TITLE
お気に入りが複数同時に選択されてしまう

### ISSUE THREAD

**Issue by azusa-tomita** [saucer-jp/comic-release-date#4]
http://www.taiyosha.co.jp/comic/comic1505_date2.html
嘘喰い　３７  
嘘喰い　３８
と並んでいるときにお気に入りをクリックすると両方選択されます

**Comment by saucer-jp** [comment]
@azusa-tomita あざます！

実はこれ意図した挙動で、漫画本の巻数部分は削除して判定するように作っています。未来の月に「嘘喰い ３９」とかが出てきた時にハイライトされるように〜という意図でっす。

**Comment by azusa-tomita** [comment]
https://dl.dropboxusercontent.com/u/5025335/lgtm/ij00002.gif
